project:
  type: website
  output-dir: docs

website:
  title: "VB's Notes and Ramblings"
  description: "AI and ML field notes, talks, and learnings from Vaibhav/ VB"
  site-url: "https://vaibhavs10.github.io"
  image: "/images/social-card.jpg"
  image-alt: "VB's website social card"
  favicon: images/favicon.png
  open-graph:
    site-name: "VB's Notes and Ramblings"
  twitter-card:
    card-style: summary_large_image
    site: "@reach_vb"
    creator: "@reach_vb"
  navbar:
    background: none
    right:
      - about.qmd
      - now.qmd
      - icon: twitter
        href: https://twitter.com/reach_vb
format:
  html:
    theme:
      light: [default, custom.scss]
    css: styles.css
    mainfont: "Courier New"
    fontsize: 1em
    linestretch: 1.7
    page-layout: article
    toc: true
    canonical-url: true
    html-math-method: katex
